### DISCUSSION TITLE
Help to get this working

### DISCUSSION THREAD

**Discussion by Casburggraaf** [sablierapp/sablier#113] [Q&A]
Wow looks amazing and something i was looking for a long time.
But i dont think it would work, i have a dev-setup with a lot of sites.
Main docker-compose.yml with traefik and some tooling apps(mailhog enz.)
And a sites folder with folders into into it for every sites(lamp stacks) with each a separate docker-compose file
I use labels for config of taefik and routing to the nginx container.
Right now i manually do a docker compose down/up to enable a site(running 100+ sites is taking to much resources), so this solution would be amazing.
Is there a way to get this working for my settup?

My setup
main docker-compose file:

```
version: "3.7"

services:
  reverse-proxy:
    container_name: traefik
    image: traefik:v2.6
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --providers.file.directory=/app/certificates
      - --providers.file.watch=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - ./config/traefik/dynamic:/etc/traefik/dynamic
      - ./config/traefik/certificates:/app/certificates:ro
    environment:
      LOCAL_IP: "${LOCAL_IP}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docker-traefik.rule=Host(`traefik.test`) || Host(`www.traefik.test`)"
      - "traefik.http.routers.docker-traefik.entrypoints=websecure"
      - "traefik.http.services.docker-traefik.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_proxy"
```
 My dynamic file only has:
 
```
 http:
  serversTransports:
    ignore-self-signed:
      insecureskipverify: true
```

My docker-compose of my lemp stack
```

version: "3.7"
services:
  nginx:
    image: nginx:latest
    container_name: ${APP_NAME}-nginx
    volumes:
      - "./config/nginx/:/etc/nginx/templates/"
      - ./src:/var/www/html:rw,cached
    environment:
      - "NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf"
    depends_on:
      - app
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)${DOMAIN_ADDITIONAL}"
      - "traefik.http.routers.${APP_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${APP_NAME}.priority=1"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_proxy"
    restart: unless-stopped

  mysql:
    image: mariadb:latest
    container_name: ${APP_NAME}-mysql

  php:
    container_name: php
    env_file:
      - .env
    user: "${UID}:${GID}"
    networks:
      - default
      - mailhog

  phpmyadmin:
    image: phpmyadmin
    container_name: ${APP_NAME}-phpmyadmin
    volumes:
      - ./config/phpmyadmin.ini:/usr/local/etc/php/conf.d/phpmyadmin.ini
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}-pma.rule=Host(`phpmyadmin.${DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME}-pma.entrypoints=websecure"
      - "traefik.http.services.${APP_NAME}-pma.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_proxy"
    environment:
      PMA_HOST: "${DB_HOST}"
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    restart: unless-stopped

  redis:
    image: bitnami/redis:latest
    profiles: ["redis"]
    container_name: ${APP_NAME}-redis
    environment:
      - REDIS_MAXMEMORY=256m
      - REDIS_PASSWORD=password
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:6.8.16
    container_name: ${APP_NAME}-elasticsearch
    environment:
      - discovery.type=single-node
    profiles: ["elasticsearch"]
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}-ela.rule=Host(`${DOMAIN}`) && PathPrefix(`/_elasticsearch`)"
      - "traefik.http.routers.${APP_NAME}-ela.entrypoints=websecure"
      - "traefik.http.routers.${APP_NAME}-ela.priority=10"
      - "traefik.http.services.${APP_NAME}-ela.loadbalancer.server.port=9200"
      - "traefik.http.routers.${APP_NAME}-ela.middlewares=traefik-strip"
      - "traefik.http.middlewares.traefik-strip.stripprefix.prefixes=/_elasticsearch"
      - "traefik.docker.network=traefik_proxy"
    restart: unless-stopped

networks:
  default:
    name: network_${APP_NAME}
  traefik:
    name: traefik_proxy
    external: true
  mailhog:
    name: mailhog
    external: true
```

How i work now. The main compose is always on, and i do a docker compose up -d and docker compose down if i'm working on a site
