### DISCUSSION TITLE
Help with setting up Sablier with Traefic Plugin

### DISCUSSION THREAD

**Discussion by tam481** [sablierapp/sablier#128] [General]
Hi
I love the idea of Sablier.

I need help with getting it to work with Traefik

The main question I have is about the plugin for Traefik: do you use the plugin in place of the Sablier container or alongside it?

Here is my Traefik static config:

```
experimental:
  plugins:
    sablier:
      moduleName: "github.com/acouvreur/sablier"
      version: "v1.2.0"
```

This is the dynamic config file:
```
http:
  middlewares:
    sablier:
      plugin:
        sablierUrl: http://sablier:10000  # The sablier URL service, must be reachable from the Traefik instance
        names: ytapp-svc               # Comma separated names of containers/services/deployments etc.
        sessionDuration: 1m               # The session duration after which containers/services/deployments instances are shutdown
        # You can only use one strategy at a time
        # To do so, only declare `dynamic` or `blocking`

        # Dynamic strategy, provides the waiting webui
        dynamic:
          displayName: My Title       # (Optional) Defaults to the middleware name
          showDetails: true           # (Optional) Set to true or false to show details specifcally for this middleware, unset to use Sablier server defaults
          theme: hacker-terminal      # (Optional) The theme to use
          refreshFrequency: 5s        # (Optional) The loading page refresh frequency

        # Blocking strategy, waits until services are up and running
        # but will not wait more than `timeout`
        # blocking: 
        #   timeout: 1m
```

ytapp-svc is the name of the service for the container I want to shutdown when not in use. This is the config part in the dynamic configuration file for Traefik:

```
routers:
  ytapp-rtr:
    rule: "Host(`ytapp.domain.lan`)"
    entryPoints:
      - "web-ep"
    middlewares:
      - sablier@file
    service: "ytapp-svc"

services:
    ytapp-svc:
      loadBalancer:
        servers:
        - url: "http://ytapp:7442"
```

Traefik shows "sablier@file" under HTTP Middlewares with its status as "Success"

Assuming you only need the plugin, I set up the above and added sablier@file as the middleware for the http router for ytapp but when I start it both the Middleware and the app show "plugin: invalid configuration: no configuration or too many plugin definition"

Please help.

**Comment by tam481** [comment]
Just wanted to ask that I looked at the e2e examples and I am even more confused because they seem to show that you need both the plugin and the container which begs the question: what is the point of the plugin if you're using the container as well?

Also, 
image: acouvreur/sablier:local as the image for the container does not work. When you start the container it generates the following error "Error response from daemon: manifest for acouvreur/sablier:local not found: manifest unknown: manifest unknown"

**Comment by acouvreur** [comment]
Hello @tam481 !

So basically, Sablier is an API first. You can read a few things about it here: https://github.com/acouvreur/sablier#api

But this will not be the common use case for everybody. More than that, I think few people would like to manually hit the API to start a container.

So in order to automatically start containers by name, reverse proxies integrations are being built. These middleware do the API calls to Sablier instead of you.

So you'd need the container Sablier, you can use the version you want, I'd recommand you to use the latest stable version, which at this point is 1.2.0. So use acouvreur/sablier:1.2.0.

And then to load your middleware with the same version to your Traefik instance.

>  "plugin: invalid configuration: no configuration or too many plugin definition"

I'm not sure if it's on Sablier middleware ends for this issue, I look it up more closely later.

Is this more clear to you?

**Comment by tam481** [comment]
Thank you so much @acouvreur for making the time to explain how this works. That makes things a lot clearer now.

In essence the Sablier container does the work of starting and stopping containers.

The plugin intercepts requests to the shutdown container via Traefik, for example, and sends the relevant API calls to the Sablier container to start the container the user is trying to access. This is why you need both. One to do the actual work and the other to effectively send the commands that tell Sablier which container to start.

In terms of configuration, I've set up a sablier.yaml file as follows:

```
provider:
  # Provider to use to manage containers (docker, swarm, kubernetes)
  name: docker 
server:
  # The server port to use
  port: 10000 
  # The base path for the API
  base-path: /
storage:
  # File path to save the state (default stateless)
  file: /data/state.json
sessions:
  # The default session duration (default 5m)
  default-duration: 5m
  # The expiration checking interval. 
  # Higher duration gives less stress on CPU. 
  # If you only use sessions of 1h, setting this to 5m is a good trade-off.
  expiration-interval: 20s
logging:
  level: info
strategy:
  dynamic:
    # Custom themes folder, will load all .html files recursively (default empty)
    custom-themes-path:
    # Show instances details by default in waiting UI
    show-details-by-default: true
    # Default theme used for dynamic strategy (default "hacker-terminal")
    default-theme: shuffle
    # Default refresh frequency in the HTML page for dynamic strategy
    default-refresh-frequency: 5s
  blocking:
    # Default timeout used for blocking strategy (default 1m)
    default-timeout: 1m
```

I have more questions, if I may:

- Where should the configuration be? Do I need to configure both the container and the plugin with the plugin via the Traefik dynamic config file and the container via its own yaml file?
- How do I configure the containers to use the Sablier middleware?
- I noticed that in the configurations for the plugin, there is "Display Name" option. Shouldn't this be the name of the container that you are trying to access?
- Is it important to specify the "names" of containers to be started and shutdown by Sablier?
- Is this how Sablier knows which containers it can shutdown? Like the question above, shouldn't this be any container that uses the Sablier middleware anyway?

Thank you for looking into the config error in my original post.
