### DISCUSSION TITLE
Struggling to understand how to add to existing Traefik

### DISCUSSION THREAD

**Discussion by jumblies** [sablierapp/sablier#144] [Q&A] [answered]
Thanks for taking this on.  It has been desired by the community for a while.  I think I understand the architecture but can't get it working. I've been watching for how to achieve this since seeing the now defunct free heroku dynos.  

Bear with me as I'm not very facile with traefik.  

I did clone the repo and when launching from the repo it works exactly as advertised.  My difficulty is translating it to my existing traefik.  

What I'm trying to achieve is to have dokuwiki shut down when not needed and restart when I try to reach the site.  

Traefik docker-compose.yaml
```
version: '3'
services:
  traefikv2:
    image: "traefik:latest"
    container_name: "traefikv2"
    restart: always
    command:
      - "--api.insecure"
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=glamke@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--providers.file.directory=/file"
      - "--providers.file.watch=true"
      - "--accesslog.filePath=/log/access.log"
      - "--accesslog.filters.statuscodes=400-499"
      - "--experimental.plugins.sablier.modulename=github.com/acouvreur/sablier"
      - "--experimental.plugins.sablier.version=v1.3.0"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "certs:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/home/glamke/docker/traefikv2/file:/file"
      - "/home/glamke/docker/traefikv2/log/:/log/"

    networks:
      - websecure


volumes:
  certs: 

networks:
  websecure:
    external: true
```

What I'd like is to add it to one site but I get lost on the dynamic setup.  I have the dynamic config for dokuwiki below which I think I copied off an issue or discussion but it doesn't do anything and I get 404 errors:

sablier.yaml (dynamic config)
```
http:
    middlewares:
        my-sablier:
            plugin:
                sablier:
                    dynamic:
                        displayName: My Title
                        refreshFrequency: 5s
                        showDetails: "true"
                        theme: hacker-terminal
                    names: dokuwiki
                    sablierUrl: http://sablier:10000
                    sessionDuration: 1m
```

**Comment by acouvreur** [comment, marked as answer]
Hi @jumblies !

So, you need to understand the following:

1. ✅ You load Sablier middleware using 
    ```yaml
     - "--experimental.plugins.sablier.modulename=github.com/acouvreur/sablier"
     - "--experimental.plugins.sablier.version=v1.3.0"
      ```
2. ✅ You then create the middleware definition/configuration in `sablier.yaml`
3. You then need to link your router (the one that actually route to your docu wiki) with the middleware, e.g.:
    ```yaml
    routers:
      dokuwiki:
        rule: PathPrefix(`/dokuwiki`)
      entryPoints:
        - "http"
      middlewares:
        - my-sablier@file
      service: "dokuwiki"
    ```

This is really important, because we don't actually know the underlying container from the route.
So this is why you specify `names: dokuwiki`

Starting with release `1.4.0` (you can use the beta for now, `1.4.0-beta.2` you can use group instead of container name which will remove you all the hassle to figure out the actual container name.

Let's say you have

```yaml
services:
  dokuwiki:
    image: dokuwiki:latest
```

Simply add the following:

```yaml
services:
  dokuwiki:
    image: dokuwiki:latest
    labels:
      - sablier.enable=true
      - sablier.group=dokuwiki
```

And change your middleware for 
```diff
http:
    middlewares:
        my-sablier:
            plugin:
                sablier:
                    dynamic:
                        displayName: My Title
                        refreshFrequency: 5s
                        showDetails: "true"
                        theme: hacker-terminal
-                    names: dokuwiki
+                    group: dokuwiki
                    sablierUrl: http://sablier:10000
                    sessionDuration: 1m
```

Do you confirm that you have a sablier instance running and accessible from traefik (same internal network, reachable by http://sablier:10000).

You have to understand the reverse proxy integration 
![image](https://user-images.githubusercontent.com/22034450/229331203-4cda1b0d-bfe5-4db2-a9c1-440ae99dc9d8.png)

All plugins just do request to the actual sablier server.

The server needs to figure out which container to bring up and down, and reverse proxies API are not tighly coupled to container, which is why you have to provide metadata on names and group.

It's also worth noting that you can start multiple containers.

**Comment by jumblies** [comment]
Thanks for the response.  

Taking a stepwise approach, I confirm I have the sablier beta container running on port 10000

sablier docker-compose.yaml
```
version: "3.7"

services:
  sablier:
    image: acouvreur/sablier:beta
    ports:
      - 10000:10000
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    command:
      - start
      - --provider.name=docker
    labels:
      - traefik.enable=true
      # Dynamic Middleware
      - traefik.http.middlewares.dynamic.plugin.sablier.names=sablier_whoami_1
      - traefik.http.middlewares.dynamic.plugin.sablier.sablierUrl=http://sablier:10000
      - traefik.http.middlewares.dynamic.plugin.sablier.sessionDuration=1m
      - traefik.http.middlewares.dynamic.plugin.sablier.dynamic.theme=hacker-terminal
      # Blocking Middleware
      - traefik.http.middlewares.blocking.plugin.sablier.names=sablier_whoami_1
      - traefik.http.middlewares.blocking.plugin.sablier.sablierUrl=http://sablier:10000
      - traefik.http.middlewares.blocking.plugin.sablier.sessionDuration=1m
      - traefik.http.middlewares.blocking.plugin.sablier.blocking.timeout=30s

```
with the log showing:
```
sablier_1  | time="2023-04-02T18:17:40Z" level=info msg="(version=beta, branch=beta, revision=eacfca9ce95629003cf856f218f43ac1a44c1f7e)"
sablier_1  | time="2023-04-02T18:17:40Z" level=info msg="using provider \"docker\""
sablier_1  | time="2023-04-02T18:17:40Z" level=info msg="initialized storage to /etc/sablier/state.json"
sablier_1  | time="2023-04-02T18:17:40Z" level=info msg="server listening :10000"
```

And I can reach it using curl:
```
curl http://localhost:10000/health
OK
```

This brings up the point that I don't have an internal network that connects traefik to sablier and that seems like a fundamental flaw.  

I think I'll get closer to your example in the repo if I move sablier inside the traefik docker compose file.  Does that sound right?
