### DISCUSSION TITLE
Trying to get a clear picture of nginx integration

### DISCUSSION THREAD

**Discussion by vutsalsinghal** [sablierapp/sablier#161] [Q&A] [answered]
Hi @acouvreur 

Thank you for this project! I went through all the docs and I'm trying to understand how to integrate it with my existing nginx setup. Would appreciate if you could shed some light

My docker-compose.yml
```
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_container
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/includes:/etc/nginx/includes
    entrypoint: "/bin/sh -c 'while :; do sleep 6h; nginx -s reload; done & nginx -g \"daemon off;\"'"
    network_mode: "host"
    restart: unless-stopped

  sablier:
    image: acouvreur/sablier:latest
    container_name: sablier_container
    command:
      - start
      - --configFile=/etc/sablier/sablier.yml
    volumes:
      - ./sablier/sablier.yml:/etc/sablier/sablier.yml
      - ./sablier/themes:/etc/sablier/themes # added ghost.html in themes folder
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"
    restart: unless-stopped
  
  whoami:
    image: containous/whoami:latest
    container_name: whoami_container
    command:
       - --port=9098
    labels:
      - sablier.enable=true
      - sablier.group=app_grp
    network_mode: "host"
    restart: unless-stopped
```
sablier.yml
```
provider:
  name: docker
server:
  port: 9097
  base-path: /
# storage:
  # file: /etc/sablier/state.json
sessions:
  default-duration: 5m
  expiration-interval: 20s
logging:
  level: debug
strategy:
  dynamic:
    custom-themes-path:
    show-details-by-default: true
    default-theme: ghost
    default-refresh-frequency: 5s
  blocking:
    default-timeout: 1m
```
nginx.conf
```
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/default.error.log warn;
pid        /var/run/nginx.pid;

load_module "modules/ngx_http_js_module.so";

events {
    worker_connections  1024;
}


http {
    include /etc/nginx/mime.types;
    default_type text/html;

    log_format main '[x_forwarded="$http_x_forwarded_for"] [$time_local] [status=$status] [host=$host] ["$request"] '
                      '[bytes=$body_bytes_sent] [referer="$http_referer"] '
                      '[agent="$http_user_agent"]';

    access_log  /var/log/nginx/default.access.log  main;

    sendfile        on;
    keepalive_timeout  65;

    # Gzip Settings
    gzip on;
    gzip_disable "msie6";
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;

    include /etc/nginx/conf.d/*.conf;
}
```
conf.d/personal.conf
```
js_import "conf.d/sablier.js";

server {
    listen 80;
    listen [::]:80;
    server_name _;
    access_log off;
}

upstream whoami_backend {
    server 172.12.0.1:9098;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name who.exmaple.com;
    include includes/wildcard-certs;

    subrequest_output_buffer_size 32k;
    set $sablierUrl /sablier;
    set $sablierSessionDuration 1m;

    location /sablier/ {
        internal;
        proxy_method GET;
        proxy_pass http://172.12.0.1:9097/;
    }

    location @whoami {
        proxy_pass http://whoami_backend;
    }

    location /dynamic/whoami_container {
        set $sablierDynamicShowDetails true;
        set $sablierDynamicRefreshFrequency 5s;
        set $sablierNginxInternalRedirect @whoami;
        set $sablierGroup app_grp;
        set $sablierDynamicName "whoami";
        set $sablierDynamicTheme ghost;
        js_content sablier.call;
    }
}
```
- `sablier.js` is in `/etc/nginx/conf.d` in the container.

Everything is up and running (no errors). Now the expectation is - if the `whoami_container` is down and I try to visit `who.exmaple.com`, sablier will show status_page while it brings the whoami_container up and then once the container is up, it will reload the browser to the whoami_container. Right?

Error in nginx logs
```
2023/07/13 18:04:10 [error] 10#10: *14 js exception: TypeError: cannot get property "split" of undefined
    at querystring.stringify (native)
    at createDynamicUrl (/etc/nginx/conf.d/sablier.js:78)
    at buildRequest (/etc/nginx/conf.d/sablier.js:64)
    at call (/etc/nginx/conf.d/sablier.js:6)
, client: ::1, server: who.example.com, request: "GET /dynamic/whoami_container HTTP/1.1", host: "who.example.com"
```

If whoami_container is already running then there is no issue but if I manually stop and try to navigate to the page, nothing happens. Is there any fault in my config?

EDIT: SOLUTION

Updating the following in `conf.d/personal.conf` worked!
```
location /dynamic/whoami_container {
        set $sablierDynamicShowDetails true;
        set $sablierDynamicRefreshFrequency 5s;
        set $sablierNginxInternalRedirect @whoami;
        set $sablierNames "whoami_container";
        set $sablierDynamicName "whoami";
        set $sablierDynamicTheme ghost;
        js_content sablier.call;
    }
```
---
Question: After the container was up, the url in browser is still `https://who.example.com/dynamic/whoami_container`. How do I make it redirect to `https://who.example.com` ?

EDIT: SOLUTION

Updated the following in `sablier.js`
Changed `r.internalRedirect(config.internalRedirect);` to `r.return(302, config.internalRedirect);` in function `call()`
