### DISCUSSION TITLE
How to set up Sablier with NGINX Proxy Manager?

### DISCUSSION THREAD

**Discussion by saschabrockel** [sablierapp/sablier#174] [Q&A]
Hey, I'm not using Nginx but Nginx proxy manager and it does not seem so easy to run Sablier with it. At least I don't know how. Or do I necessarily need another Nginx instance? If we could find it out together I would create a manual on how to do it.

**Comment by saschabrockel** [comment]
I guess it's not really possible...

**Comment by acouvreur** [comment]
I'm not familiar with NPM, for it to work with Sablier we would need to overwrite the default templates for routing

**Reply by saschabrockel** [reply]
I actually tried. But it didn't work. That's why I'm asking.

**Reply by acouvreur** [reply]
Cam you share what you actually tried so far ?

It might help building something for NPM

**Reply by saschabrockel** [reply]
I tried what you said. I have created my own modified config files and mapped them as volumes for the NPM container.
![Screenshot 2023-08-27 060936](https://github.com/acouvreur/sablier/assets/33376463/d1668d54-4070-44b3-babf-415da288b70c)

In there I tried to mix up the existing things and add sablier specific things:

`nginx_docker_classic.conf`:

```
js_import conf.d/sablier.js;

# internal docker resolver, see /etc/resolv.conf on proxy container
resolver 127.0.0.11 valid=10s ipv6=off;

server {
    listen 80;
    listen [::]:80;

    set $forward_scheme "http";
    set $server "127.0.0.1";
    set $port "80";

    server_name localhost-nginx-proxy-manager;
    access_log /data/logs/fallback_access.log standard;
    error_log /data/logs/fallback_error.log warn;
    include conf.d/include/assets.conf;
    include conf.d/include/block-exploits.conf;
    include conf.d/include/letsencrypt-acme-challenge.conf;

    location / {
            index index.html;
            root /var/www/html;
    }

  subrequest_output_buffer_size 32k;

  set $sablierUrl /sablier;
  set $sablierSessionDuration 1m;

  location @whoami {
    # Use variable in order to refresh DNS cache
    set $whoami_server whoami;
    proxy_pass http://$whoami_server:80;
    proxy_set_header Host localhost:8080; # e2e test compliance
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location @nginx {
    # Use variable in order to refresh DNS cache
    set $nginx_server nginx;
    proxy_pass http://$nginx_server:80;
    proxy_set_header Host localhost:8080; # e2e test compliance
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /sablier/ {
    internal;
    proxy_method GET;
    proxy_pass http://sablier:10000/;
  }

  location /dynamic/whoami {
    set $sablierDynamicShowDetails true;
    set $sablierDynamicRefreshFrequency 5s;
    set $sablierNginxInternalRedirect @whoami;
    set $sablierNames docker_classic_e2e-whoami-1;
    set $sablierDynamicName "Dynamic Whoami";
    set $sablierDynamicTheme hacker-terminal;
    js_content sablier.call;
  }

  location /blocking/whoami {
    set $sablierNginxInternalRedirect @whoami;
    set $sablierNames docker_classic_e2e-whoami-1;
    set $sablierBlockingTimeout 30s;
    js_content sablier.call;
  }

  location /multiple/nginx {
    set $sablierDynamicShowDetails true;
    set $sablierDynamicRefreshFrequency 5s;
    set $sablierNginxInternalRedirect @nginx;
    set $sablierNames docker_classic_e2e-nginx-1,docker_classic_e2e-whoami-1;
    set $sablierDynamicName "Multiple Whoami";
    set $sablierDynamicTheme hacker-terminal;
    js_content sablier.call;
  }

  location /multiple/whoami {
    set $sablierDynamicShowDetails true;
    set $sablierDynamicRefreshFrequency 5s;
    set $sablierNginxInternalRedirect @whoami;
    set $sablierNames docker_classic_e2e-nginx-1,docker_classic_e2e-whoami-1;
    set $sablierDynamicName "Multiple Whoami";
    set $sablierDynamicTheme hacker-terminal;
    js_content sablier.call;
  }

  location /healthy/nginx {
    set $sablierDynamicShowDetails true;
    set $sablierDynamicRefreshFrequency 5s;
    set $sablierNginxInternalRedirect @nginx;
    set $sablierNames docker_classic_e2e-nginx-1;
    set $sablierDynamicName "Healthy Nginx";
    set $sablierDynamicTheme hacker-terminal;
    js_content sablier.call;
  }
}

# First 443 Host, which is the default if another default doesn't exist
server {
        listen 443 ssl;
        listen [::]:443 ssl;

        set $forward_scheme "https";
        set $server "127.0.0.1";
        set $port "443";

        server_name localhost;
        access_log /data/logs/fallback_access.log standard;
        error_log /dev/null crit;
        include conf.d/include/ssl-ciphers.conf;
        ssl_reject_handshake on;

        return 444;
}server {
        listen 80;
        listen [::]:80;

        set $forward_scheme "http";
        set $server "127.0.0.1";
        set $port "80";

        server_name localhost-nginx-proxy-manager;
        access_log /data/logs/fallback_access.log standard;
        error_log /data/logs/fallback_error.log warn;
        include conf.d/include/assets.conf;
        include conf.d/include/block-exploits.conf;
        include conf.d/include/letsencrypt-acme-challenge.conf;

        location / {
                index index.html;
                root /var/www/html;
        }
}

# First 443 Host, which is the default if another default doesn't exist
server {
        listen 443 ssl;
        listen [::]:443 ssl;

        set $forward_scheme "https";
        set $server "127.0.0.1";
        set $port "443";

        server_name localhost;
        access_log /data/logs/fallback_access.log standard;
        error_log /dev/null crit;
        include conf.d/include/ssl-ciphers.conf;
        ssl_reject_handshake on;

        return 444;
}
```

If I remember it right I just changed this line in the `nginx.conf`:

`load_module modules/ngx_http_js_module.so;`

That's the first big main problem. How the hell do I get the JS module to get `sablier.js` working?

**Reply by saschabrockel** [reply]
Have you ever tried to continue with it?

**Reply by HoreaM** [reply]
I'm really interested as well, is there a way to make Sablier work with NPM? It would be sensational.

**Reply by acouvreur** [reply]
If NPM supports Proxy WASM filters, it might be working with #284

I've successfully ran it with Nginx and Kong wasm plugin.

So If NPM provides such plugin, it may work.

**Reply by ViktorTrojan** [reply]
I also need help with this, I have seen this:

https://nginxproxymanager.com/advanced-config/

So I tried setting the config in ``/data/nginx/custom/http.conf`` but nothing seemed to happen?


I just don't know what im doing and need help.

maybe the location can be set here?
![image](https://github.com/user-attachments/assets/a5499e2f-8c82-4981-95d4-26b77b6ce6fd)

As far as I can tell from the examples, when you enter http://localhost/whoami it should call sablier and it handles the conainer. but I don't want it to work for localhost but rather a custom domain like https://whoami.example.com.

**Reply by josselinonduty** [reply]
Any updates?

**Reply by webysther** [reply]
I was able to use, here my working sample:

```
services:
  zotero:
    # https://hub.docker.com/r/linuxserver/zotero
    # https://www.zotero.org/support/changelog
    image: lscr.io/linuxserver/zotero:7.0.32
    container_name: app-research
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    networks:
      - zotero
    shm_size: "1gb"
    labels:
      sablier.enable: true
      sablier.group: zotero
      traefik.enable: true
      traefik.docker.allownonrunning: true
      traefik.http.middlewares.zotero.plugin.sablier.group: zotero
      traefik.http.middlewares.zotero.plugin.sablier.sablierUrl: http://sablier.lan:10000
      traefik.http.middlewares.zotero.plugin.sablier.sessionDuration: 30m
      traefik.http.middlewares.zotero.plugin.sablier.dynamic.displayName: Zotero
      traefik.http.routers.zotero.middlewares: zotero
      traefik.http.routers.zotero.rule: Host(`zotero.example.com`)
      traefik.http.services.zotero.loadbalancer.server.port: 3000
    restart: unless-stopped

  traefik:
    # https://github.com/traefik/traefik/releases
    image: ghcr.io/traefik/traefik:3
    container_name: app-research-proxy
    command:
      - --experimental.plugins.sablier.modulename=github.com/sablierapp/sablier-traefik-plugin
      - --experimental.plugins.sablier.version=v1.1.0
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=zotero
      - --providers.docker=true
    networks:
      - zotero
    ports:
      - 3016:80 # zotero.example.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  sablier:
    # https://github.com/sablierapp/sablier/releases
    image: ghcr.io/sablierapp/sablier:1.11.1
    container_name: app-ondemand
    environment:
      SABLIER_PROVIDER_NAME: docker
      SABLIER_SESSIONS_DEFAULT_DURATION: 1h
      SABLIER_PROVIDER_AUTO_STOP_ON_STARTUP: true
      SABLIER_STRATEGY_DYNAMIC_DEFAULT_THEME: "ghost"
      SABLIER_STRATEGY_DYNAMIC_DEFAULT_REFRESH_FREQUENCY: 1s
    networks:
      - zotero
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

networks:
  zotero:
    name: zotero
```

Now create a host in NPM with zotero.example.com and point to traefik:3016.

With this aproach build of nginx is not necessary, and traefik works as a sidecar-proxy.

@acouvreur you maybe use this for all reversa with build and wasm to drop support for this method and use only a sidecar-proxy, which you maybe expose in a container as sablier-middleware and allow everyone use, no matter what is the reverse-proxy. Hope helps!
