### DISCUSSION TITLE
Problem with setting up Traefik Middleware

### DISCUSSION THREAD

**Discussion by Cloufish** [sablierapp/sablier#303] [Q&A] [answered]
I struggle with setting up Sablier Middleware in Traefik.

I use Docker Swarm + Traefik
Probably the culprit lies in traefik-conf.yml
Should I define middleware on top of `entrypoint:   http:`?
There are a lot of configuration examples in Discussion, but I wanted to stick to the website documentation

**web-app docker-compose**:
```yml
version: '3'

services:
  rust-book:
    container_name: rust-book
    image: peaceiris/mdbook:v0.4.28
    stdin_open: true
    tty: true
    ports:
      - "80"
    networks:
      - web
      - rust-book
    volumes:
      - /home/swarm/books/rust-book:/book
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.rust-book.rule=Host(`rust-book.home`)"
        - "traefik.http.services.rust-book.loadbalancer.server.port=3000"
        - "traefik.docker.network=web"
        - "io.portainer.accesscontrol.users=admin"
        - "traefik.http.routers.rust-book.tls=true"
        - "sablier.enable=true"    # I ADDED THIS
        - "sablier.group=non-essential"    # I ADDED THIS
        - "traefik.docker.lbswarm=true"    # I ADDED THIS
    command:
      - serve
      - --hostname
      - '0.0.0.0'



networks:
  rust-book:
    driver: overlay
    attachable: true
    name: rust-book
  web:
    external: true
    name: web
```

**sablier docker-compose**:
```yml
version: "3.5"


services:
  sablier:
    image: acouvreur/sablier:1.6.1
    container_name: sablier
    ports:
      - "80"
    networks:
      - web
      - sablier
    volumes:
      - '/home/swarm/sablier/sablier.yaml:/etc/sablier/sablier.yml'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.sablier.rule=Host(`sablier.home`)"
        - "traefik.http.services.sablier.loadbalancer.server.port=10000"
        - "traefik.docker.network=web"
        - "io.portainer.accesscontrol.users=admin"
        - "traefik.http.routers.sablier.tls=true"
    command:
      - start
      - --provider.name=swarm


networks:
  sablier:
    driver: overlay
    attachable: true
    name: sablier
  web:
```

**sablier.yml config**:
```yml
provider:
  name: swarm
server:
  port: 10000
  base-path: /
storage:
  file:
sessions:
  default-duration: 5m
  expiration-interval: 20s
logging:
  level: info
strategy:
  dynamic:
    custom-themes-path:
    show-details-by-default: true
    default-theme: ghost
    default-refresh-frequency: 5s
  blocking:
    default-timeout: 1m
```

**traefik-conf.yml**:
```yml
### Static Configuration
log:
  level: DEBUG
api:
  dashboard: true

serversTransport:
  insecureSkipVerify: true
  rootCAs:
    - /certs/rootCA.pem

certificatesResolvers:
  rootCAs:
    - /certs/rootCA.pem

entryPoints:
  web:
    address: ":80"

  gitea-ssh:
    address: ":222"

  webhttp:
    address: ":8081"

  websecure:
    address: ":443"

providers:
  swarm:
    exposedByDefault: false
  file:
    directory: /configuration/
    watch: true
providers:
  swarm:
    exposedByDefault: false
  file:
    directory: /configuration/
    watch: true
# For Sablier to work:
experimental:
  plugins:
    sablier:
      moduleName: "github.com/acouvreur/sablier"
      version: "v1.6.1"


http:
  middlewares:
    my-sablier:
      plugin:
        sablier:
          group: non-essential
          dynamic:
            displayName: The service starts...
            refreshFrequency: 5s
            showDetails: "true"
            theme: ghost
          sablierUrl: https://sablier:10000
          sessionDuration: 1m

```

![image](https://github.com/acouvreur/sablier/assets/32965886/8ed31a4e-884b-4c13-8dcb-44a04fd00778)
![image](https://github.com/acouvreur/sablier/assets/32965886/9098b8b1-ad5b-4a71-9028-1dddf3ed39ee)
![image](https://github.com/acouvreur/sablier/assets/32965886/d216df7c-0303-418c-9a98-bd0855882f0b)
