### DISCUSSION TITLE
How do I start a single container with traefik?

### DISCUSSION THREAD

**Discussion by luigir-it** [sablierapp/sablier#307] [General]
Hi. I'm using this plugin with traefik.

Let's say I have 10 containers, each one configured with traefik using the `file` provider
Those containers are "independent" from each other, and I'd like to start only the one I'm accessing to.

Right now, I have a `plugin` section with the `names` of all the containers (comma separated list). This way, when I access a container (e.g. `3`), all 10 are started. 

```
http:
  middlewares:

    sablier-dynamic:
      plugin:
        sablier:
          names: 0,1,2,3,4,5,6,7,8,9
          sablierUrl: http://sablier-traefik:10000
          sessionDuration: 1m
          dynamic:
            displayName: Application
            refreshFrequency: 2s
            showDetails: "true"
            theme: ghost
```
Does that mean that I have to replicate the plugin section 10 times, and have only a container name per section?
