### DISCUSSION TITLE
Need help with configuration for Docker Swarm + Traefik

### DISCUSSION THREAD

**Discussion by florentin68** [sablierapp/sablier#595] [Q&A] [answered]
Hello,
Thank you for this amazing project.
I'm using Docker Swarm with multiple services.
I configured such as mentionned in SablierApp documentation (Traefik plugin with 1 middleware to test, groupname=default, Sablier service with sablier.yaml config file, labels on services I want to scale to zero, Traefik whoami for example to test).
When I try to access whoami.domain.com I get this error:
```
{
    "availableGroups": null,
    "detail": "The group you requested does not exist. It is possible that the group has not been scanned yet.",
    "error": "group default not found",
    "instance": "/api/strategies/dynamic?display_name=Loading...\u0026group=default\u0026refresh_frequency=2s\u0026session_duration=30m\u0026show_details=true\u0026theme=hacker-terminal",
    "requestGroup": "home",
    "status": 404,
    "title": "Group not found",
    "type": "https://sablierapp.dev/#/errors?id=group-not-found"
}
```
What did I miss?

**Comment by uldiseihenbergs** [comment]
Post your config. you should add group name to your service(with labels) and it should match with group name in middleware

**Comment by florentin68** [comment]
Here are config files extractions:

compose.yml

```
  whoami:
    image: traefik/whoami
    networks:
      - t2_proxy
    deploy:
      replicas: 0 # [sablier]
      labels:
        ## Traefik
        - traefik.enable=true
        - traefik.swarm.lbswarm=true
        ## HTTP Routers
        - 'traefik.http.routers.whoami.entrypoints=https'
        - 'traefik.http.routers.whoami.rule=Host(`whoami.${DOMAINNAME}`)'
        ## HTTP Middlewares
        - 'traefik.http.routers.whoami.middlewares=my-sablier@file'
        ## HTTP Services
        - 'traefik.http.routers.whoami.service=whoami'
        - 'traefik.http.services.whoami.loadbalancer.server.port=80'
        ## Diun
        - diun.enable=true
        - diun.watch_repo=false
        ## Wud
        - wud.watch=true
        ## Sablier
        - sablier.enable=true
        - sablier.group=default
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  # Sablier - On-demand services
  sablier:
    image: ghcr.io/sablierapp/sablier
    networks:
      - t2_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $DOCKERDIR/volumes/sablier/sablier.yml:/etc/sablier/sablier.yml
    deploy:
      labels:
        ## Traefik
        - traefik.enable=false
        ## Diun
        - diun.enable=true
        - diun.watch_repo=false
        ## Wud
        - wud.watch=true
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
```

traefik-middleware.yml

```
    my-sablier:
      plugin:
        sablier:
          dynamic:
            displayName: "Loading..."
            refreshFrequency: 2s
            showDetails: "true"
            theme: hacker-terminal
          group: default
          #names: general_whoami,dashy,heimdall,phpmyadmin,pgadmin,ldapadmin,grafana#,nginx
          sablierUrl: http://sablier:10000
          sessionDuration: 30m
```

**Comment by uldiseihenbergs** [comment]
post your /etc/sablier/sablier.yml too.
and if you use group, sablier will start and stop all services at once..
if you set sublier logging to trace, what it contains at sablier service startup? it should write info about groups and services into it..

**Comment by florentin68** [comment]
Sorry, I missed it:
sablier.yml
```
provider:
  # Provider to use to manage containers (docker, swarm, kubernetes)
  name: swarm
server:
  # The server port to use
  port: 10000
  # The base path for the API
  base-path: /
storage:
  # File path to save the state (default stateless)
  file:
sessions:
  # The default session duration (default 5m)
  default-duration: 5m
  # The expiration checking interval.
  # Higher duration gives less stress on CPU.
  # If you only use sessions of 1h, setting this to 5m is a good trade-off.
  expiration-interval: 20s
logging:
  level: info
strategy:
  dynamic:
    # Custom themes folder, will load all .html files recursively (default empty)
    custom-themes-path:
    # Show instances details by default in waiting UI
    show-details-by-default: false
    # Default theme used for dynamic strategy (default "hacker-terminal")
    default-theme: hacker-terminal
    # Default refresh frequency in the HTML page for dynamic strategy
    default-refresh-frequency: 5s
  blocking:
    # Default timeout used for blocking strategy (default 1m)
    default-timeout: 1m
```

With trace loglevel instead of info I get this at startup:

```
general_sablier.1.mghd9m9l9h4j@photon1-fm    | 7:57PM INF sablier/sablier.go:25 running Sablier version (version=1.9.0, branch=HEAD, revision=31464c38b5859738e4b1c9f1962de833d47db001)
general_sablier.1.mghd9m9l9h4j@photon1-fm    | 7:57PM INF docker/docker.go:28 connection established with docker provider=docker version=27.3.1 api_version=1.47
general_sablier.1.mghd9m9l9h4j@photon1-fm    | 7:57PM INF theme/parse.go:12 theme found path=embedded/ghost.html
general_sablier.1.mghd9m9l9h4j@photon1-fm    | 7:57PM INF theme/parse.go:19 successfully added theme path=embedded/ghost.html
general_sablier.1.mghd9m9l9h4j@photon1-fm    | 7:57PM INF theme/parse.go:12 theme found path=embedded/hacker-terminal.html
general_sablier.1.mghd9m9l9h4j@photon1-fm    | 7:57PM INF theme/parse.go:19 successfully added theme path=embedded/hacker-terminal.html
general_sablier.1.mghd9m9l9h4j@photon1-fm    | 7:57PM INF theme/parse.go:12 theme found path=embedded/matrix.html
general_sablier.1.mghd9m9l9h4j@photon1-fm    | 7:57PM INF theme/parse.go:19 successfully added theme path=embedded/matrix.html
general_sablier.1.mghd9m9l9h4j@photon1-fm    | 7:57PM INF theme/parse.go:12 theme found path=embedded/shuffle.html
general_sablier.1.mghd9m9l9h4j@photon1-fm    | 7:57PM INF theme/parse.go:19 successfully added theme path=embedded/shuffle.html
general_sablier.1.mghd9m9l9h4j@photon1-fm    | 7:57PM INF server/server.go:43 starting  listen=:10000 startup=76.924µs mode=release
```

Provider = docker, not swarm. It seems the config file isn't parsed, no?

File attributes in host:
```
root@photon1-fm [ /share/homes/docker/volumes/sablier ]# ls -al
total 12
drwxr-x---  2 root root 4096 May 26 21:55 .
drwxr-xr-x 63 root adm  4096 May 25 21:35 ..
-rw-r-----  1 root root 1076 May 26 21:55 sablier.yml
```
