### DISCUSSION TITLE
All i'm getting are 404's

### DISCUSSION THREAD

**Discussion by schumi2004** [sablierapp/sablier#604] [General]
I'm running Traefik and have added below config.
I see the container that i want to suspend and start being shutdown by Sablier but it never gets up. 
No hacker-terminal screen just a 404 directly.
What have i missed? 
Also tried 1.9.0 first but thought since the plugin is 1.8.5 i downgrade to 1.8.5

In Traefik stack (compose) i have added Sablier service:

```
  sablier:
    image: sablierapp/sablier:1.8.5
    container_name: sablier
    command:
      - start
      - --provider.name=docker
    networks:
      - proxy
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
```

The container i want to suspend and start added these labels:

```
    labels:
    # Sablier config
      - sablier.enable=true
      - sablier.group=apps
```

In traefik added this plugin:

```
experimental:
  plugins:
    sablier:
      moduleName: "github.com/sablierapp/sablier"
      version: "v1.8.5"
```

And this is the configured middleware:

```
  middlewares:
    sablier:
      plugin:
        sablier:
          group: apps
          dynamic:
            displayName: Please wait while the app is loading
            refreshFrequency: 5s
            showDetails: "true"
            theme: hacker-terminal
          sablierUrl: http://sablier:10000
          sessionDuration: 1m
```
