### DISCUSSION TITLE
start iperf3 server using docker

### DISCUSSION THREAD

**Discussion by alx-xlx** [sablierapp/sablier#610] [Q&A]
```
iperf3-selfhosted.example.xyz {
    sablier http://192.168.0.114:10000 {
        group iperf3
        session_duration 5m
        blocking {
            timeout 1m
        }
    }
    reverse_proxy http://192.168.0.114:5201
}
```

I have the above Caddyfile and the below docker-compose.yml file

```
version: '3.9'
services:
  iperf3:
    container_name: iperf3-server
    image: networkstatic/iperf3
    ports:
        - '5201:5201'
    command: '-s'
    tty: true
    stdin_open: true
    # restart: unless-stopped
    labels:
      - sablier.enable=true
      - sablier.group=iperf3
    healthcheck:
      test: ["CMD", "sh", "-c", "timeout 2 iperf3 -c 127.0.0.1 -t 1 || exit 1"]
      interval: 1s
      timeout: 5s
      retries: 20
```

but when I do `iperf3 -c iperf3-selfhosted.example.xyz` then it doesnt start the `iperf3-server` server. What am I doing wrong here ?
