### ISSUE TITLE
Sablier UI only shows when non-existent docker is configured

### ISSUE THREAD

**Issue by bblaha** [sablierapp/sablier#151]
I feel like this is a config issue, but I have now spent hours trying to find it and I can't.

Bug description
I have Sablier configured and I can get it to run only, when I enter a docker into the config that is not existing. i.e. the following works
```
    my-sablier:
        plugin:
            sablier:
                dynamic:
                    displayName: My Title
                    refreshFrequency: 5s
                    showDetails: "true"
                    theme: ghost
                group: default
                names: PasswordPusherEphemeral,whoami,nginx
                sablierUrl: http://sablier:10000
                sessionDuration: 1m
```

and I can call sablier.example.com or whoami.example.com. Here is the thing, however: I do not have a container called nginx. And it throws that error. When I remove nginx (or any other non-existent container for that matter, such as follows...
```
    my-sablier:
        plugin:
            sablier:
                dynamic:
                    displayName: My Title
                    refreshFrequency: 5s
                    showDetails: "true"
                    theme: ghost
                group: default
                names: PasswordPusherEphemeral,whoami
                sablierUrl: http://sablier:10000
                sessionDuration: 1m
```
I cannot reach the UI anymore, neither via sablier.example.com nor via whoami.example.com. Instead I get a 404 page not found.

Also, when I DO add the non-existent container, ALL containers that Sablier is assigned to as middleware only show the Sablier UI, they never forward and even reloading does not get me to the actual service.

I am running 1.4.0-beta3 on both the container and the traefik plugin.
