### ISSUE TITLE
Doc: Missing information or clarification might be needed for kubernetes.

### ISSUE THREAD

**Issue by ArKam** [sablierapp/sablier#328]
I’m currently planning to use sablier as a traefik plugin within a kubernetes cluster but I didn’t find a clear explanation if installing our own instance of the sablier repository is required?

I’ve followed the traefik documentation to add a plugin to it and this documentation involve to give traefik the plugin github URL and the release version we want to use.

But neither traefik or sablier (To my knowledge, sorry if I’m wrong) does clarify if we need to make it run on kubernetes as an app deployed or if traefik indeed use the information given on the yaml configuration file to retrieve it on its own and make it run on its own?

I’m telling me that I’m suppose to run sablier as a deployment and tell traefik how to find it but I’m really clueless on this topic right now and traveling out of home so I can’t really « Just try and find out ».

Sorry if I’m wrong.

**Comment by acouvreur** [comment]
You can take a look at the following guide:
https://acouvreur.github.io/sablier/#/guides/code-server-traefik-kubernetes

But yes, traefik plugin only tells you how ton install the plugin. But the plugin itself handles the call for you on every call to the actual Sablier API.

You need to have Sablier running on its own and available to Traefik.

**Comment by acouvreur** [comment]
For the docs, you can also look at https://acouvreur.github.io/sablier/#/getting-started

**Comment by acouvreur** [comment]
Merci a toi :)

How do you think I could improve the understanding that Sablier needs to be deployed on its own ?

Should it be part of the plugin description ?

**Comment by facorazza** [comment]
> Merci a toi :)
> 
> How do you think I could improve the understanding that Sablier needs to be deployed on its own ?
> 
> Should it be part of the plugin description ?

I believe it should be mentioned here: https://acouvreur.github.io/sablier/#/providers/kubernetes.

> In order to use the **docker** provider you can configure the provider.name property.

This should probably be fixed as well.

**Comment by gorositopablo** [comment]
@ArKam not sure if you could implement it without issues finally, but it worth mention this comment https://github.com/acouvreur/sablier/issues/62#issuecomment-1375820824 to workaround using the `blocking` strategy.

It works great for me and without that service type `ExternalName` it would not have been possible for me to use the blocking strategy (ideal for APIs).

So, if it were up to me, I would add it to the documentation as well.


```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: yourapp-svc
  namespace: demo-ns
spec:
  type: ClusterIP
  selector:
    app: yourapp
  ports:
    - port: 80
      targetPort: 80
---
# https://github.com/acouvreur/sablier/issues/62
apiVersion: v1
kind: Service
metadata:
  name: yourapp-svc-proxy
  namespace: demo-ns
spec:
  type: ExternalName
  externalName: yourapp-svc.demo-ns.svc.cluster.local
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: yourapp-client
  namespace: demo-ns
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: >-
        Host(`example.com`) &&
        PathPrefix(`/yourapp`)
      middlewares:
        - name: yourapp-sablier
      services:
        - kind: Service
          name: yourapp-svc-proxy
          port: 80
          namespace: demo-ns
```
