### ISSUE TITLE
(Kubernetes) labels not public

### ISSUE THREAD

**Issue by sftim** [sablierapp/sablier#449]
**Describe the bug**

Sablier uses private [labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/) (private because there is no `/` in the key). Example:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  labels:
    app: whoami
    sablier.enable: "true"
    sablier.group: mygroup
…
```

**Context**
 - Sablier version: 1.8.1
 - Provider: any Kubernetes
 - Reverse proxy: _not applicable_
 - Sablier running inside a container? _not relevant_

**Expected behavior**
The label keys for Sablier are public; for example:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  labels:
    app.kubernetes.io/name: whoami # also good practice, but not core to THIS issue
    sablierapp.dev/enable: "true"
    sablierapp.dev/group: mygroup
…
```

Using public label keys is good practice, helps people find the documentation a little more easily, and avoids conflicting with organizations' own policies and conventions for private labels.

**Additional context**
Typically when Kubernetes-compatible projects adopt the official label convention(s), they add support for the new way; then they deprecate the old way (using private label keys), but continue to support it for many releases. The documentation recommends the new-style, public label keys.

Read https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set for Kubernetes' documentation about public vs. private label keys.
