### ISSUE TITLE
Loading screen fails to display

### ISSUE THREAD

**Issue by taiwan-king** [sablierapp/sablier#450]
When using `traefik:v3.1.4` with `sablier:v1.7.0`, the loading screen displays normally. However, after upgrading to `sablier:v1.8.1`, the loading screen fails to display, though all functionalities still work correctly.
The `refreshFrequency` function also does not work correctly.

**Comment by acouvreur** [comment]
Hello @taiwan-king, can you give me more details on what you're actually seeing ?
Maybe the log details ?

What is the exact sablier image that you are using ?

**Comment by taiwan-king** [comment]
{"time":"2024-11-17T02:01:11Z","level":"info","msg":"172.19.0.4 - d53c09da6c6c [17/Nov/2024:02:01:11 +0000] \\&#34;GET /api/strategies/dynamic\\&#34; 200 6329 \\&#34;\\&#34; \\&#34;Go-http-client/1.1\\&#34; (1ms)","clientIP":"172.19.0.4","dataLength":"6329","hostname":"d53c09da6c6c","latency":"1","method":"GET","path":"/api/strategies/dynamic","referer":"","statusCode":"200","userAgent":"Go-http-client/1.1"}

sablierapp/sablier:1.8.1

**Comment by taiwan-king** [comment]
traefik config
---------------------
experimental:
  plugins:
    sablier:
      moduleName: "github.com/sablierapp/sablier"
      version: "v1.8.1"
-----------------------
browserquest config
-----------------------
http:
  routers:
    browserquest:
      rule: "Host(`browserquest.taiwan-homecloud.us.kg`)"
      entryPoints:
        - "http"
      middlewares:
        - "browserquest"
      service: "browserquest"
    websocket:
      rule: "Host(`browserquest.taiwan-homecloud.us.kg`)"
      entryPoints:
        - "websocket"
      middlewares:
        - "browserquest"
      service: "websocket"

  middlewares:
    browserquest:
      plugin:
        sablier:
          names: BrowserQuest-PHP
          dynamic:
            refreshFrequency: 5s
            showDetails: "true"
            theme: ghost
          sablierUrl: http://sablier:10000
          sessionDuration: 1m
          
  services:
    browserquest:
      loadBalancer:
        servers:
          - url: "http://192.168.10.253:807"
    websocket:
      loadBalancer:
        servers:
          - url: "http://192.168.10.253:8000"
--------------------------------

**Comment by ViktorTrojan** [comment]
Can confirm this is the case for me aswell, using nginx proxy manager

**Comment by acouvreur** [comment]
I've just tried with the latest verison and everything works on my side.

However, when there is an error in the configuration, the feedback is currently very bad.

Do you have any error on your Sablier logs ?

**Comment by ViktorTrojan** [comment]
No logs. It just does not show a loading screen, just white until it shows the webpage

**Comment by taiwan-king** [comment]
> 我剛剛嘗試了最新版本，一切都對我有利。
> 
> 但是，當配置出現錯誤時，目前反饋非常糟糕。
> 
> 您的 Sablier 紀錄上有什麼錯誤嗎？

My configuration should not have any issues,  
because everything worked fine when I was using version 1.7.0.  
The only thing I did was upgrade the version.  
Additionally, there are no error logs displayed.

**Comment by ViktorTrojan** [comment]
Same for me, I set it up with version 1.8.1 I think and had no loading screen. Downgraded to 1.7.0 and login screen works.

I'm not sure but the redirect seems somewhat slow, it's not really slow but I would assume that there would be no noticeable delay?

**Comment by PacaAlpaca** [comment]
Also have this problem with 1.8.1
**No** major changes in configuration since previous version.

traefik.yml:
```
experimental:
  plugins:
    sablier:
      moduleName: "github.com/sablierapp/sablier"
      version: "v1.8.1"
```
fileConfig.yml:
```
http:
  routers:
    guacamole:
      entryPoints:
        - "websecure"
      rule: 'Host(`guacamole.xxx.xxx`)'
      service: guacamole
      tls: {}
      middlewares:
        - "guacamole-sablier@file"
...
  services:
    guacamole:
      loadBalancer:
        serversTransport: "xxxxx"
        servers:
          - url: "http://xxxxx:xxxx"
...
  middlewares:
    guacamole-sablier:
      plugin:
        sablier:
          group: guacamole
          dynamic:
            displayName: guacamole
            refreshFrequency: 30s
            showDetails: "true"
            theme: "shuffle"
          sablierUrl: http://sablier:10000
          sessionDuration: 20m
```

Before container starts (with nextcloud - 5s, with guacamole ~1min) I see cloudflare error page - "host not working" instead of sablier loading screen/theme

**Comment by acouvreur** [comment]
Is it possible for any of you to create a repository to reproduce the issue ?

That'd be amazing, thanks

**Comment by DaveHOnCode** [comment]
I even had it with the basic WhoamI example using docker as provider and Caddy as reverse proxy.

I would like to switch back to version 1.7.0, to rule out a configuration error on my side, but there is no package available for that on the docker hub. If you could provide that, I would be very thankful

**Comment by DaveHOnCode** [comment]
Could it be an issue if its only one container to start up?
At least I'm facing that issue only if I use One-Container Configurations (i. e. Stirling PDF). While using multiple container docker files, there is no issues.

Thanks for your effort!

**Comment by CarbonNeuron** [comment]
I think I figured it out. It is returning a 502 status code when the service is not up yet. And cloudflare is replacing that with a error page.

**Comment by DaveHOnCode** [comment]
No that doesn’t make sense to me. It’s just displaying a white page, without any error code and it also doesn’t reload, even then the page is finally upOn 11. Dec 2024, at 19:45, CarbonNeuron ***@***.***> wrote:﻿
I think I figured it out. It is returning a 502 status code when the service is not up yet. And cloudflare is replacing that with a error page.

**Comment by taiwan-king** [comment]
> No that doesn’t make sense to me. It’s just displaying a white page, without any error code and it also doesn’t reload, even then the page is finally upOn 11. Dec 2024, at 19:45, CarbonNeuron ***@***.***> wrote:﻿ I think I figured it out. It is returning a 502 status code when the service is not up yet. And cloudflare is replacing that with a error page. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

You can find the older version here: https://github.com/acouvreur/sablier.

**Comment by CarbonNeuron** [comment]
One person said they received a cloudflare error message. I'm getting a 502 while the service is down which cloudflare replaces.

**Comment by ardavan-ansari** [comment]
Same issue, I'm using Traefik and Cloudflare. The containers are stopped and started correctly, but the loading page is not displaying (502 error page, replaced by Cloudflare).

Downgrading to 1.7 fixes the issue.

**Comment by dbogatov** [comment]
Same. `acouvreur/sablier:1.7.1-beta.1` works with the same config.

**Comment by alx-xlx** [comment]
i get the same issue, i reinserted my external ssd and saw that none of the containers are starting correctly, just showing a white screen. But now after like 2 restarts and when i check after 6hrs then everything works fine.

this is very inconsistent and unreliable software to use, there is no information on what is happening. There should be some sort of fix for this issue. 

White screen isn't the best way to undrstand what has gone wrong.

**Comment by ViktorTrojan** [comment]
@alx-xlx this is open source software. A fix is mentioned, which is using an older version. If you want you can fix this issue and open a pull request, otherwise don't complain about open source software

**Comment by hitesh-singh** [comment]
Can confirm this issue still persist with Sablier v1.8.2 and Traefik v3.3.1

**Comment by Karl-V-HRR** [comment]
I have conducted some tests, and for me `acouvreur/sablier:1.8.0-beta.8` is the last image which displays the loading screen correctly.

*Sablier compose file*
```
services:
  sablier:
    container_name: Sablier
    image: acouvreur/sablier:1.8.0-beta.8
    command:
      - start
      - --provider.name=docker
      - --logging.level=trace
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/sablier.yaml:/etc/sablier/sablier.yaml
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.monitor-only=true
    networks:
      - Sablier
networks:
  Sablier:
    external: true
```
*(Back instance) Caddyfile*
```
http://jellyfin.mydomain.com {
        route / {
                sablier http://sablier:10000 {
                        group Jellyfin
                        session_duration 10m
                        dynamic {
                                display_name Jellyfin
                        }
                }
        }
        reverse_proxy   jellyfin:8096
}
```

**Comment by acouvreur** [comment]
Do any of you still experience that issue ?

Maybe it's related to #506 

Do you have an healthcheck defined for your services that fail to display ?

What's probably happening is that your container is "started" but not ready to handle requests. In that case, the reverse proxy should return a 5xx error

**Comment by Karl-V-HRR** [comment]
Hi @acouvreur !
I have not used Sablier since my report on this issue, but for the sake of giving a proper feedback I have tested whether the situation has improved.
Everything seems to work fine now with the update — so `v1.8.3`. And you are absolutely right : containers that lacked a proper healthcheck would not display the loading screen ; adding a healthcheck in the compose.yaml file solved this issue for me. The new warnings in the logs definitely helped in debugging that.

Strangely enough I was not able to reproduce the consistent failed loading screen I was experiencing then, which would occur regardless of whether the Docker application I was trying to launch had a proper healthcheck or not. Perhaps there was a misconfiguration on my end, or the Caddy module has been updated in the meantime.

Either way, I think the issue is now properly solved. Thank you for your dedication !

**Comment by taiwan-king** [comment]
Already tested—adding the health check does make the loading screen display properly.

**Comment by extrafein** [comment]
For all who need a quick fix for their containers, just add the heathcheck section to your docker-compose.yml

```
services:
  thunderbird:
    image: kasmweb/thunderbird:1.16.1
    container_name: thunderbird
    healthcheck:
      test: ["CMD", "true"]
```
