### ISSUE TITLE
404 error on /api/strategies/dynamic

### ISSUE THREAD

**Issue by Carson-Shaar** [sablierapp/sablier#474]
**Describe the bug**
I am using the dynamic strategy with sablier to provide a page both when deployments are coming up and to scale down unused deployments. I am seeing this when i access one of these deployments in sablier logs:

```
time="2024-12-11T18:10:49Z" level=warning msg="removed_ip- sablier-deployment-699b895cc8-zmqvk [11/Dec/2024:18:10:49 +0000] \"GET /api/strategies/dynamic\" 404 0 \"\" \"Go-http-client/1.1\" (1ms)" clientIP="removed_ip" dataLength=0 hostname=sablier-deployment-699b895cc8-zmqvk latency=1 method=GET path=/api/strategies/dynamic referer= statusCode=404 userAgent=Go-http-client/1.1
```

This results in just an empty webpage in the browser even when pod has come up

**Context**
 - Sablier version: 1.8.1
 - Provider: Kubernetes 1.31
 - Reverse proxy: Traefik v3.2.1
 - Sablier running inside a container? Yes Kubernetes deployment 

**Expected behavior**
200 response from sablier to display loading page and then forward to app when pod is ready

**Additional context**
I am using the Traefik Kubernetes gateway api and Sablier itself is running in the Traefik namespace. Here are my configurations:

Traefik:
```
experimental:
  plugins:
    sablier:
      moduleName: github.com/sablierapp/sablier
      version: v1.8.1
  # -- Defines whether all plugins must be loaded successfully for Traefik to start
  abortOnPluginFailure: false
```
  
Sablier:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sablier
  namespace: traefik
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sablier
  namespace: traefik
rules:
  - apiGroups:
      - apps
      - ""
    resources:
      - deployments
      - deployments/scale
      - statefulsets
      - statefulsets/scale
    verbs:
      - patch
      - get
      - update
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sablier
  namespace: traefik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sablier
subjects:
  - kind: ServiceAccount
    name: sablier
    namespace: traefik
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sablier-deployment
  namespace: traefik
  labels:
    app: sablier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sablier
  template:
    metadata:
      labels:
        app: sablier
    spec:
      serviceAccountName: sablier
      containers:
      - name: sablier
        image: sablierapp/sablier:1.8.1
        args: 
        - "start"
        - "--provider.name=kubernetes"
        - "--sessions.default-duration=5m"
        - "--sessions.expiration-interval=20s"
        resources:
          limits:
            cpu: "200m"
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "64Mi"
        ports:
          - containerPort: 10000
---
apiVersion: v1
kind: Service
metadata:
  name: sablier
  namespace: traefik
spec:
  selector:
    app: sablier
  ports:
    - protocol: TCP
      port: 10000
      targetPort: 10000
```
      

Middleware:
```
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: sablier
  namespace: notebook
spec:
  plugin:
    sablier:
      group: default
      dynamic:
        displayName: Waiting for Zero-True Notebook
        refreshFrequency: 10s
        showDetails: "true"
        theme: shuffle
      sablierUrl: http://sablier.traefik.svc.cluster.local:10000
      sessionDuration: 3m
```

Deployment and HTTP Route:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: notebook
  labels:
    app: my-deployment
    sablier.enabled: "true"
    sablier.group: default
    
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute-ex
  namespace: notebook
spec:
  hostnames:
  - notebook.example.com
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: traefik-gateway
      namespace: traefik
      sectionName: https-notebook
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: my-service-ns
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: "/example/route"
    filters:
    - type: ExtensionRef
      extensionRef:
        group: traefik.io
        kind: Middleware
        name: sablier
```
