### ISSUE TITLE
Sablier not working when upgrading from caddy 2.7 to 2.8.4

### ISSUE THREAD

**Issue by accforgithubtest** [sablierapp/sablier#478]
I have had a working set-up, using caddy + docker-proxy + sablier for a while now, using version 2.7 and things have been mostly working fine.
The custom builds are from [serfriz/caddy-custom-builds](https://github.com/serfriz/caddy-custom-builds/tree/main/caddy-ratelimit-dockerproxy-sablier).

When I upgrade to the latest version 2.8.4, all the applications that do not have sablier enabled are working fine.
For applications that have sablier enabled, it looks like they are not getting started by sablier, I end up getting a blank page in the browser.

If I start the container manually, then I am able to access the application from browser.

I do not see any error logs in both caddy and sablier containers.

Below is the critical bits of the compose files -

**Context**
 - Sablier version: 2.7 -> 2.8.4
 - Provider: docker 27.4.0
 - Reverse proxy: Caddy (with docker proxy and sablier enabled). 2.7 works fine. 2.8.4 has issues.
 - Sablier running inside a container? Yes.

**Expected behavior**
Expect sablier to start the containers and redirect to the correct page.

With the below, version 2.7works fine, while the latest (2.8.4) doesnt work.

```yaml
services:
  caddy:
    image: serfriz/caddy-ratelimit-dockerproxy-sablier:2.7
    # image: serfriz/caddy-ratelimit-dockerproxy-sablier:latest
    container_name: caddy
    restart: always
    environment:
      - CADDY_INGRESS_NETWORKS=default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certificates:/certs:ro
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
      - 10000:10000
    labels:
      ### Global config for caddy and sablier to work together
      caddy.order: sablier before reverse_proxy

  sablier:
    image: sablierapp/sablier:latest
    container_name: sablier
    restart: always
    environment:
      - PROVIDER_NAME=docker
      - LOGGING_LEVEL=info
      - SESSIONS_DEFAULT_DURATION=15m
      - SESSIONS_EXPIRATION_INTERVAL=1m
      - STRATEGY_BLOCKING_DEFAULT_TIMEOUT=30s
      # - STRATEGY_DYNAMIC_DEFAULT_REFRESH_FREQUENCY=1s
      - STRATEGY_DYNAMIC_SHOW_DETAILS_BY_DEFAULT=true
      - STRATEGY_DYNAMIC_DEFAULT_THEME=shuffle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      caddy: sablier.local.host
      caddy.reverse_proxy: "{{upstreams 10000}}"
      caddy.tls: "caddy path to self signed certificates"

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: no
    environment:
      - DOZZLE_ENABLE_ACTIONS=true
      # - DOZZLE_LEVEL=debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/data
    labels:
      caddy: logs.local.host
      caddy.reverse_proxy: "{{upstreams 8080}}"
      caddy.tls: "caddy path to self signed certificates"
      caddy.sablier.enable: true
      caddy.sablier.names: dozzle
      caddy.sablier.sessionDuration: 15m
      caddy.sablier.dynamic:

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: no
    environment:
      - FB_NOAUTH=noauth
    volumes:
      - ./data:/database
      - ./config:/config
      - /mnt/test/volume:/srv
    labels:
      caddy: files.local.host
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.tls: "caddy path to self signed certificates"
      # caddy.sablier.enable: true
      # caddy.sablier.names: filebrowser
      # caddy.sablier.sessionDuration: 10m
      # caddy.sablier.dynamic:

```
