### ISSUE TITLE
Missing documentation on integrating with traefik?

### ISSUE THREAD

**Issue by quotengrote** [sablierapp/sablier#505]
Hi,

i have been trying to get sablier working with traefik. I think i must have overseen some important steps or the documentation is missing them. I assume this because on same pages there are sentences which end within a word.

So please let me know where in my condiguration there is the error. ;-)

# Compose File of the Project that should be started on demand

```yaml
---
services:
  grampsweb: &grampsweb
    container_name: grampsweb
    image: ghcr.io/gramps-project/grampsweb:v25.1.1  # version
    restart: unless-stopped
    pull_policy: missing
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2048M"
    security_opt:
      - no-new-privileges=true
#    ports:
#      - "6483:5000"  # host:docker
    environment:
      GRAMPSWEB_TREE: "Gramps Web"  # will create a new tree if not exists
      GRAMPSWEB_CELERY_CONFIG__broker_url: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_CELERY_CONFIG__result_backend: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_RATELIMIT_STORAGE_URI: redis://grampsweb_redis:6379/1
      GRAMPSWEB_EMAIL_HOST: "docker10.mgrote.net"
      GRAMPSWEB_EMAIL_PORT: "1025"
      GRAMPSWEB_EMAIL_USE_TLS: "false"
      GRAMPSWEB_DEFAULT_FROM_EMAIL: "gramps@mgrote.net"
    depends_on:
      - grampsweb_redis
    volumes:
      - gramps_users:/app/users  # persist user database
      - gramps_index:/app/indexdir  # persist search index
      - gramps_thumb_cache:/app/thumbnail_cache  # persist thumbnails
      - gramps_cache:/app/cache  # persist export and report caches
      - gramps_secret:/app/secret  # persist flask secret
      - gramps_db:/root/.gramps/grampsdb  # persist Gramps database
      - gramps_media:/app/media  # persist media files
      - gramps_tmp:/tmp
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - traefik
      - gramps
    labels:
      sablier.enable: true
      sablier.group: gramps # https://github.com/orgs/sablierapp/discussions/144

      traefik.http.routers.gramps.rule: Host(`gramps.mgrote.net`)
      traefik.enable: true
      traefik.http.routers.gramps.tls: true
      traefik.http.routers.gramps.tls.certresolver: resolver_letsencrypt
      traefik.http.routers.gramps.entrypoints: entry_https
      traefik.http.services.gramps.loadbalancer.server.port: 5000

      traefik.http.routers.gramps.middlewares: sablier_dynamic@file

  grampsweb_celery:
    <<: *grampsweb  # YAML merge key copying the entire grampsweb service config
    ports: []
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2048M"
    container_name: grampsweb-celery
    depends_on:
      - grampsweb_redis
    command: celery -A gramps_webapi.celery worker --loglevel=INFO
    healthcheck: {}
    networks:
      - gramps

  grampsweb_redis:
    image: redis:7.4.2-alpine
    container_name: grampsweb-redis
    restart: unless-stopped
    pull_policy: missing
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "512M"
    security_opt:
      - no-new-privileges=true
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - gramps

######## Volumes ########
volumes:
  gramps_users:
  gramps_index:
  gramps_thumb_cache:
  gramps_cache:
  gramps_secret:
  gramps_db:
  gramps_media:
  gramps_tmp:
######## Networks ########
networks:
  traefik:
    external: true # was macht das nochmal genau?
  gramps:

```

# Compose File of Sablier

```yaml
---
services:
  sablier:
    image: sablierapp/sablier:1.8.3
    command:
      - start
      - --configFile=/config.yml
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './config.yml:/config.yml'
    container_name: sablier
    restart: unless-stopped
    pull_policy: missing
    security_opt:
      - no-new-privileges=true
    networks:
      - traefik
    environment:
      TZ: Europe/Berlin
    labels:
      traefik.enable: true
      traefik.http.middlewares.dynamic.plugin.sablier.names: sablier-dynamic
      traefik.http.middlewares.dynamic.plugin.sablier.sablierUrl: http://sablier:10000

# alles was andere container auhc haben
# einschränen
# tags usw.
# healtcheck
# überschriten in compose files überall
######## Networks ########
networks:
  traefik:
    external: true

```

# Sablier config

```yaml
provider:
  # Provider to use to manage containers (docker, swarm, kubernetes)
  name: docker
server:
  # The server port to use
  port: 10000
  # The base path for the API
  base-path: /
storage:
  # File path to save the state (default stateless)
  file:
sessions:
  # The default session duration (default 5m)
  default-duration: 5m
  # The expiration checking interval.
  # Higher duration gives less stress on CPU.
  # If you only use sessions of 1h, setting this to 5m is a good trade-off.
  expiration-interval: 20s
logging:
  level: debug
strategy:
  dynamic:
    # Custom themes folder, will load all .html files recursively (default empty)
    custom-themes-path:
    # Show instances details by default in waiting UI
    show-details-by-default: false
    # Default theme used for dynamic strategy (default "hacker-terminal")
    default-theme: ghost
    # Default refresh frequency in the HTML page for dynamic strategy
    default-refresh-frequency: 5s
  blocking:
    # Default timeout used for blocking strategy (default 1m)
    default-timeout: 1m


# https://github.com/acouvreur/sablier/blob/main/plugins/traefik/README.md#traefik-with-docker-classic

```
# Traefik File-Provider Configuration

```yaml
http:
###### router ######
  routers:
    router_forgejo:
      rule: "Host(`git.mgrote.net`)"
      service: "service_forgejo"
      middlewares:
        - "ratelimit40@file"
      entrypoints:
        - "entry_https"
      tls:
        certresolver: resolver_letsencrypt
    router_gramps:
      rule: "Host(`gramps.mgrote.net`)"
      service: "service_gramps"
      entrypoints:
        - "entry_https"
      middlewares:
        - "sablier_dynamic@file"
      #  - "authelia@docker"
###### services ######
  services:
    service_gramps:
      loadBalancer:
        servers:
          - url: "docker10.mgrote.net:6483"
    service_forgejo:
      loadBalancer:
        servers:
          - url: "http://forgejo.mgrote.net:3000/"
###### middlewares ######
  middlewares:
    ratelimit40:
      rateLimit:
        average: 40
        burst: 80
        sourceCriterion:
          ipStrategy:
            depth: 2
    allowlist_localnet:
      ipallowlist:
        sourcerange:
          - 192.168.2.0/24
          - 10.25.25.0/24
          - 192.168.48.0/24 # docker
          - 172.18.0.0/16 # gitea-act-runner
        ipstrategy:
          depth: 0 # https://doc.traefik.io/traefik/middlewares/http/ipallowlist/#ipstrategydepth
    sablier_dynamic:
      plugin:
        sablier:
          group: "gramps"
          sablierUrl: http://sablier:10000
          sessionDuration: 1m
          dynamic:
            displayName: Dynamic Whoami
            theme: ghost

```

# Links

- Repository with MR: https://git.mgrote.net/mg/homeserver/pulls/294

**Comment by acouvreur** [comment]
Hello @quotengrote 

> I assume this because on same pages there are sentences which end within a word.
I'm not sure I understand your point, could you help me out on this one?

---

Otherwise, everything looks good, but maybe you did not import the plugin to Traefik properly ?

Sablier works with both the Sablier contianer and the [sablier traefik plugin](https://plugins.traefik.io/plugins/6715d1d37dd5a6c3095befd4/sablier).

![Image](https://github.com/user-attachments/assets/d77e64b3-cc9c-40d7-8b2c-382d3e9d1f49)

Can you check the Traefik logs to make sure the Sablier middleware is properly loaded ?

**Comment by quotengrote** [comment]
Hio, i attached the traefik config an a screenshot that shows the middleware.

```yaml
global:
  sendAnonymousUsage: false

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik
  file:
    filename: /etc/traefik/file-provider.yml # Datei für alte/externe Services

entryPoints:
  entry_http:
    address: :80
    http: # Umleitung http zu https
      redirections:
        entryPoint:
          to: entry_https
          scheme: https
          permanent: true
  entry_https:
    address: :443
  entry_ssh:
    address: :2222 # wenn hier zusätzliche Ports eingetragen werden, müssen diese auch in der docker-compose.yml als Ports gemappt werden

# letsencrypt
certificatesResolvers:
  resolver_letsencrypt:
    acme:
      email: "michael.grote@posteo.de"
      storage: "/etc/traefik/acme/acme.json"
#      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
       # zum Testen, da Staging kein Rate-Limiting einsetzt
      tlsChallenge: true

log:
  level: INFO # TRACE , DEBUG , INFO , WARN , ERROR , FATAL , PANIC

accessLog: {}

api:
  insecure: true
  dashboard: true # unter Port 8081 erreichbar

ping: {} # für healthcheck

###### plugins ######
experimental:
  plugins:
    sablier:
      moduleName: "github.com/sablierapp/sablier"
      version: "v1.8.3"

```

![Image](https://github.com/user-attachments/assets/60ea4379-633f-4546-a8ca-f3e66e489c66)
![Image](https://github.com/user-attachments/assets/deaec21b-65d1-4f4c-92ef-c3c836eda973)
