### ISSUE TITLE
No CSS and/or Javascript get loaded

### ISSUE THREAD

**Issue by Svenum** [sablierapp/sablier#506]
**Describe the bug**
The plugin works, but I dont get the loading screen shown.

![Image](https://github.com/user-attachments/assets/d24f4d68-bfa7-41ac-96f1-792e261f9c46)

**Context**
 - Sablier version: v1.8.3
 - Provider: docker
 - Reverse proxy: traefik v3.3.3
 - Sablier running inside a container? yes

**Comment by Svenum** [comment]
I dont know exactly. It worked a time with version v1.8.1 but after some time not anymore. Then I updated sablier today, hopping thats the problem. But it wasn't.

**Comment by acouvreur** [comment]
Did you also change the reverse proxy (Traefik) configuration ?

Can you show what the response headers are ?

**Comment by Svenum** [comment]
The only thing I changed was the version after updating the sablier docker

`traefik.yaml`:
```yaml

experimental:
  plugins:
    sablier:
      moduleName: "github.com/sablierapp/sablier"
      version: "v1.8.3"
```

`dynconfig`:
```yaml
http:
  middlewares:
    pdf-sablier:
      plugin:
        sablier:
          group: pdf 
          dynamic:
            displayName: StirlingPDF
            showDetails: "true"
          sablierUrl: http://sablier:10000
          sessionDuration: 15m

    hb-handbrake:
      plugin:
        sablier:
          group: hb
          dynamic:
            displayName: Handbrake
            showDetails: "true"
          sablierUrl: http://sablier:10000
          sessionDuration: 12h

    gm-sablier:
      plugin:
        sablier:
          group: gm
          dynamic:
            displayName: Guacamole
            showDetails: "true"
          sablierUrl: http://sablier:10000
          sessionDuration: 60m

    jf-sablier:
      plugin:
        sablier:
          group: jf
          dynamic:
            displayName: Jellyseerr
            showDetails: "true"
          sablierUrl: http://sablier:10000
          sessionDuration: 10m

  ## ROUTER ##
  routers:
    stirlingpdf:
      entryPoints:
      - https
      rule: 'Host(`svc-stirlingpdf.unraid.holypenguin.net`) || Host(`pdf.holypenguin.net`)'
      service: stirlingpdf
      middlewares:
      - pdf-sablier

    handbrake:
      entryPoints:
      - https
      rule: 'Host(`svc-handbrake.unraid.holypenguin.net`) || Host(`handbrake.holypenguin.net`)'
      service: handbrake
      middlewares:
      - hb-handbrake

    guacamole:
      entryPoints:
      - https
      rule: 'Host(`svc-guacamole.unraid.holypenguin.net`) || Host(`guacamole.holypenguin.net`)'
      service: guacamole
      middlewares:
      - gm-sablier

    jellyseerr:
      entryPoints:
      - https
      rule: 'Host(`svc-jellyseerr.unraid.holypenguin.net`) || Host(`jellyseerr.holypenguin.net`)'
      service: jellyseerr
      middlewares:
      - jf-sablier

  ## SERVICES ##
  services:
    stirlingpdf:
      loadBalancer:
        servers:
          - url: http://stirlingpdf:8080/

    handbrake:
      loadBalancer:
        servers:
          - url: http://handbrake:5800

    guacamole:
      loadBalancer:
        servers:
          - url: http://guacamole:8080/

    jellyseerr:
      loadBalancer:
        servers:
          - url: http://jellyseerr:5055/

```

**Comment by bohregard** [comment]
I'm having the exact same issue with a fresh setup of Sablier + Traefik.
```
experimental:
  plugins:
    sablier:
      moduleName: "github.com/sablierapp/sablier"
      version: "v1.8.3"
```

The response I get back when I try to navigate is a 502:
```
HTTP/2 502 
referrer-policy: strict-origin-when-cross-origin
strict-transport-security: max-age=63072000; includeSubDomains; preload
x-content-type-options: nosniff
x-forwarded-proto: https
x-robots-tag: none,noarchive,nosnippet,notranslate,noimageindex
x-xss-protection: 1; mode=block
date: Sun, 09 Feb 2025 06:39:49 GMT
X-Firefox-Spdy: h2
```
