### ISSUE TITLE
[Documentation] Inconsistencies between config options

### ISSUE THREAD

**Issue by seupedro** [sablierapp/sablier#507]
Hi! First of all, thank you for this awesome project! I'm using and loving it! (: 

I was reading the documentation and I got confused. Why the config names varies from the config [sablier.yaml](https://sablierapp.dev/#/configuration?id=configuration-file) file?

```yaml
. . . 
sessions:
  default-duration: 5m <-- is different
  expiration-interval: 20s

strategy:
  dynamic:
    custom-themes-path: <-- is different
    show-details-by-default: false <-- is different
    default-theme: hacker-terminal <-- is different
    default-refresh-frequency: 5s <-- is different

  blocking:
    # Default timeout used for blocking strategy (default 1m)
    default-timeout: 1m <-- is different
```

<img width="300" alt="Image" src="https://github.com/user-attachments/assets/1587cd99-a4ae-43c2-86ba-545c859d44ca" />
<img width="262" alt="Image" src="https://github.com/user-attachments/assets/561ffa28-b01b-4ed1-9a1e-06c5c7c6c6dc" />
<img width="320" alt="Image" src="https://github.com/user-attachments/assets/7c3bf406-4742-4833-ac8f-91547d9b8321" />

----

Shouldn't it be consistent across the all files?
