### ISSUE TITLE
Not working with Traefik and Docker swarm

### ISSUE THREAD

**Issue by chupacabra71** [sablierapp/sablier#530]
I am trying to test out sablier, but i think i may be missing some key piece to make it work.   I had this in discussion, but now i think it may actually be an issue.  Here is my setup: 

I added these labels to my working traefik instance: 
```
      # Enable Swarm Provider (Replaces Docker Swarm Mode from v2)
      - "--providers.swarm=true"
      - "--providers.swarm.exposedbydefault=false"
      - "--providers.swarm.network=traefik-external"
      - "--providers.swarm.allowEmptyServices=true"    ## ADDED FOR SABLIER
```

then in the plugins section i added:
```
      # Plugins
      - "--experimental.plugins.crowdsec-bouncer-traefik-plugin.modulename=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      - "--experimental.plugins.crowdsec-bouncer-traefik-plugin.version=v1.3.5"
      - "--experimental.plugins.sablier.modulename=github.com/sablierapp/sablier"           ## ADDED FOR SABLIER
      - "--experimental.plugins.sablier.version=v1.8.4"                                                            ## ADDED FOR SABLIER
```

Also in my traefik stack i have defined a service for sablier:
```
  sablier:
    image: sablierapp/sablier:1.8.4
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
    command:
      - start
      - --provider.name=docker_swarm # or swarm
      - --sessions.default-duration=5m0s 
      - --sessions.expiration-interval=1m0s
      - --strategy.blocking.default-timeout=1m0s
      - --strategy.dynamic.default-refresh-frequency=5s
      - --strategy.dynamic.default-theme=hacker-terminal
      - --strategy.dynamic.show-details-by-default=true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - traefik-internal
```

in my middlewares, i define sablier:
```
http:
  middlewares:
    global-sablier:
      plugin:
        sablier:
          group: apps
          dynamic:
            displayName: Please wait while the app is loading
            refreshFrequency: 5s
            showDetails: "true"
            theme: hacker-terminal
          sablierUrl: http://sablier:10000
          sessionDuration: 1m
```

I decided to test with a service that doesn't get used much, stirling-pdf.  in the stack for stirling i defined the middleware and labels:
```
services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:0.42.0-fat
      labels:
        - "traefik.enable=true"
        ## HTTP Routers - internal
        - "traefik.http.routers.rtr-stirlingpdf.entrypoints=websecure"
        - "traefik.http.routers.rtr-stirlingpdf.rule=Host(`pdf.${PRIMARY_DOMAIN}`)"
        - "traefik.http.routers.rtr-stirlingpdf.service=svc-stirlingpdf"
        - "traefik.http.routers.rtr-stirlingpdf.priority=10"
        ## Middlewares
        - "traefik.http.routers.rtr-stirlingpdf.middlewares=global-sablier@file"                                ## ADDED FOR SABLIER
        ## HTTP Services
        - "traefik.http.services.svc-stirlingpdf.loadBalancer.server.port=8080"
        ## Sablier labels
        - sablier.enable=true                                                                                                                 ## ADDED FOR SABLIER
        - sablier.group=apps                                                                                                                 ## ADDED FOR SABLIER  
      
```

when sablier spins up, it sucessfully stops the stirling pdf container, but then they dissapear from traefik.  
```
admin@swarm-mgr02:~$ docker service logs --no-trunc traefik_sablier -f 
traefik_sablier.1.64ciejtze7vfme0c2v5aij27s@swarm-mgr01    | 4:29PM INF app/sablier.go:33 running Sablier version (version=1.8.4, branch=HEAD, revision=2b4ba7f3ceebe8909cc2e75d354c2b90f909944e)
traefik_sablier.1.64ciejtze7vfme0c2v5aij27s@swarm-mgr01    | 4:29PM INF dockerswarm/docker_swarm.go:42 connection established with docker swarm provider=swarm version=27.5.1 api_version=1.47
traefik_sablier.1.64ciejtze7vfme0c2v5aij27s@swarm-mgr01    | 4:29PM INF storage/file.go:47 storage successfully initialized file=/etc/sablier/state.json
traefik_sablier.1.64ciejtze7vfme0c2v5aij27s@swarm-mgr01    | 4:29PM INF app/sablier.go:144 loading sessions from storage
traefik_sablier.1.64ciejtze7vfme0c2v5aij27s@swarm-mgr01    | 4:29PM INF sessions/sessions_manager.go:61 set groups old=map[] new="map[apps:[stirlingpdf_stirling-pdf stirlingpdf_db]]" diff="\u00a0\u00a0map[string][]string{\n+\u00a0\t\"apps\": {\"stirlingpdf_stirling-pdf\", \"stirlingpdf_db\"},\n\u00a0\u00a0}\n"
traefik_sablier.1.64ciejtze7vfme0c2v5aij27s@swarm-mgr01    | 4:29PM DBG discovery/autostop.go:33 found instances to stop instances="[stirlingpdf_stirling-pdf stirlingpdf_db]"
traefik_sablier.1.64ciejtze7vfme0c2v5aij27s@swarm-mgr01    | 4:29PM INF discovery/autostop.go:51 stopped unregistered instance instance=stirlingpdf_db reason="instance is enabled but not started by Sablier"
traefik_sablier.1.64ciejtze7vfme0c2v5aij27s@swarm-mgr01    | 4:29PM INF discovery/autostop.go:51 stopped unregistered instance instance=stirlingpdf_stirling-pdf reason="instance is enabled but not started by Sablier"
traefik_sablier.1.64ciejtze7vfme0c2v5aij27s@swarm-mgr01    | 4:29PM DBG app/sablier.go:94 loading themes from custom theme path path=/etc/sablier/themes
traefik_sablier.1.64ciejtze7vfme0c2v5aij27s@swarm-mgr01    | 4:29PM INF theme/parse.go:12 theme found path=embedded/ghost.html
traefik_sablier.1.64ciejtze7vfme0c2v5aij27s@swarm-mgr01    | 4:29PM INF theme/parse.go:19 successfully added theme path=embedded/ghost.html
traefik_sablier.1.64ciejtze7vfme0c2v5aij27s@swarm-mgr01    | 4:29PM INF theme/parse.go:12 theme found path=embedded/hacker-terminal.html
traefik_sablier.1.64ciejtze7vfme0c2v5aij27s@swarm-mgr01    | 4:29PM INF theme/parse.go:19 successfully added theme path=embedded/hacker-terminal.html
traefik_sablier.1.64ciejtze7vfme0c2v5aij27s@swarm-mgr01    | 4:29PM INF theme/parse.go:12 theme found path=embedded/matrix.html
traefik_sablier.1.64ciejtze7vfme0c2v5aij27s@swarm-mgr01    | 4:29PM INF theme/parse.go:19 successfully added theme path=embedded/matrix.html
traefik_sablier.1.64ciejtze7vfme0c2v5aij27s@swarm-mgr01    | 4:29PM INF theme/parse.go:12 theme found path=embedded/shuffle.html
traefik_sablier.1.64ciejtze7vfme0c2v5aij27s@swarm-mgr01    | 4:29PM INF theme/parse.go:19 successfully added theme path=embedded/shuffle.html
traefik_sablier.1.64ciejtze7vfme0c2v5aij27s@swarm-mgr01    | 4:29PM INF server/server.go:43 starting  listen=:10000 startup=81.838µs mode=debug
traefik_sablier.1.64ciejtze7vfme0c2v5aij27s@swarm-mgr01    | [GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
traefik_sablier.1.64ciejtze7vfme0c2v5aij27s@swarm-mgr01    |  - using env:      export GIN_MODE=release
traefik_sablier.1.64ciejtze7vfme0c2v5aij27s@swarm-mgr01    |  - using code:     gin.SetMode(gin.ReleaseMode)
traefik_sablier.1.64ciejtze7vfme0c2v5aij27s@swarm-mgr01    | 
traefik_sablier.1.64ciejtze7vfme0c2v5aij27s@swarm-mgr01    | [GIN-debug] GET    /health                   --> github.com/sablierapp/sablier/internal/api.(*Health).ServeHTTP-fm (3 handlers)
traefik_sablier.1.64ciejtze7vfme0c2v5aij27s@swarm-mgr01    | [GIN-debug] GET    /api/strategies/dynamic   --> github.com/sablierapp/sablier/internal/api.StartDynamic.func1 (3 handlers)
traefik_sablier.1.64ciejtze7vfme0c2v5aij27s@swarm-mgr01    | [GIN-debug] GET    /api/strategies/blocking  --> github.com/sablierapp/sablier/internal/api.StartBlocking.func1 (3 handlers)
traefik_sablier.1.64ciejtze7vfme0c2v5aij27s@swarm-mgr01    | [GIN-debug] GET    /api/themes               --> github.com/sablierapp/sablier/internal/api.ListThemes.func1 (3 handlers)
traefik_sablier.1.64ciejtze7vfme0c2v5aij27s@swarm-mgr01    | [GIN-debug] GET    /api/dynamic/themes       --> github.com/sablierapp/sablier/internal/api.ListThemes.func1 (3 handlers)

```
the services are still there but scaled to 0/0:
```
admin@swarm-mgr03:~$ docker service ls
ID             NAME                              MODE         REPLICAS   IMAGE                                                 PORTS
p6chig0lyofr   stirlingpdf_db                    replicated   0/0        postgres:17.3-alpine                                  
3ny82s9hydre   stirlingpdf_stirling-pdf          replicated   0/0        stirlingtools/stirling-pdf:0.42.0-fat                 
waz1zk60bzrp   traefik_sablier                   replicated   1/1        sablierapp/sablier:1.8.4                              
ftcuehjabbqv   traefik_traefik-proxy             replicated   1/1        traefik:v3.3.3                                        
```

since the service is removed from traefik, i get a `404 page not found` error when hitting the url for the service.  my guess is that it has something to do with not having "traefik.docker.lbswarm=true", but in the docks it says "Traefik also have [allowEmptyServices](https://doc.traefik.io/traefik/providers/docker/#allowemptyservices) option which can be used instead."  I'd rather not use lbswarm since i do want load-balancing through traefik.

> Enables Swarm's inbuilt load balancer (only relevant in Swarm Mode).
> 
> If you enable this option, Traefik will use the virtual IP provided by docker swarm instead of the containers IPs. Which means that Traefik will not perform any kind of load balancing and will delegate this task to swarm.

Any help would be greatly appreciated.

_Originally posted by @chupacabra71 in https://github.com/sablierapp/sablier/discussions/526_
