### ISSUE TITLE
Issue with multiple traefik middlewares in swarm

### ISSUE THREAD

**Issue by chupacabra71** [sablierapp/sablier#538]
**Describe the bug**
I finally got Sablier working on a single service in my swarm, thanks to @acouvreur ! i went to add a second application and it appears that the swarm is skipping the tags for some reason.   I got sablier working with my instance of stirling-pdf and that continues to operate perfectly.  i then decided to start adding other services.  I added the next service and it gets the same 404[ errrors i was getting before](https://github.com/sablierapp/sablier/issues/530) adding the `traefik.docker.lbswarm=true` label to the stirling service.   the next service is configured identically to the stirling service so i am confused as to why it would not work.  Below are some of the configuration items in case someone has an idea on what may be causing the issue. 

I have this as my definition for sablier service: 
```
  sablier:
    image: sablierapp/sablier:1.8.5
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
    command:
      - start
      - --provider.name=docker_swarm # or swarm
      - --sessions.default-duration=5m0s 
      - --sessions.expiration-interval=1m0s
      - --strategy.blocking.default-timeout=1m0s
      - --strategy.dynamic.default-refresh-frequency=5s
      - --strategy.dynamic.default-theme=hacker-terminal
      - --strategy.dynamic.show-details-by-default=true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - traefik-internal
      - traefik-external
```

i load the plugin in traefik in a dynamic config for the middleware.  in my dynamic config file i have the following:
```
    global-sablier-paperless:
      plugin:
        sablier:
          group: paperless
          dynamic:
            displayName: "Please wait while we load Paperless"
            refreshFrequency: 5s
            showDetails: "true"he 
            theme: hacker-terminal
          sablierUrl: http://sablier:10000
          sessionDuration: 1m

    global-sablier-stirling:
      plugin:
        sablier:
          group: stirling
          dynamic:
            displayName: "Please wait while we load Stirling-PDF"
            refreshFrequency: 5s
            showDetails: "true"
            theme: hacker-terminal
          sablierUrl: http://sablier:10000
          sessionDuration: 1m
```
Stirling PDF is working with these labels:
```
      labels:
        - "traefik.enable=true"
        ## Sablier labels
        - "traefik.swarm.lbswarm=true"                                                   ### FOR SABLIER
        - "sablier.enable=true"                                                           ### FOR SABLIER
        - "sablier.group=stirling"                                                            ### FOR SABLIER
        ## HTTP Routers - internal
        - "traefik.http.routers.rtr-stirlingpdf.entrypoints=websecure"
        - "traefik.http.routers.rtr-stirlingpdf.rule=Host(`pdf.${PRIMARY_DOMAIN}`)"
        - "traefik.http.routers.rtr-stirlingpdf.service=svc-stirlingpdf"
        - "traefik.http.routers.rtr-stirlingpdf.priority=10"
        ## Middlewares
        - "traefik.http.routers.rtr-stirlingpdf.middlewares=global-sablier-stirling@file"            #### FOR SABLIER
        ## HTTP Services
        - "traefik.http.services.svc-stirlingpdf.loadBalancer.server.port=8080"
```
But paperless is not working with these labels:
```
      labels:
        # Enable Traefik for this service
        - "traefik.enable=true"
        ## Sablier labels
        - "traefik.sawrm.lbswarm=true"                                                                                    ### FOR SABLIER
        - "sablier.enable=true"                                                                                           ### FOR SABLIER
        - "sablier.group=paperless"                                                                                          ### FOR SABLIER
        ## HTTP Routers - internal
        - "traefik.http.routers.rtr-paperless.rule=Host(`docs.${PRIMARY_DOMAIN}`)"
        - "traefik.http.routers.rtr-paperless.entrypoints=websecure"
        - "traefik.http.routers.rtr-paperless.service=svc-paperless"
        - "traefik.http.routers.rtr-paperless.priority=10"
        ## Middlewares
        - "traefik.http.routers.rtr-paperless.middlewares=global-forwardauth-authentik@file, global-sablier-paperless@file"      #### FOR SABLIER
        # - "traefik.http.routers.rtr-paperless.middlewares=global-forwardauth-authentik@file"
        ## HTTP Services 
        - "traefik.http.services.svc-paperless.loadbalancer.server.port=8080"
```
The only real difference i can see between these apps is that paperless has two `middlewares` defined where stirling only has the sablier middleware.  
The sablier service sees the instances and spins down both the stirling pdf, and the paperless instance.  when i go to the stirlin URL, it shows me the `hacker-terminal` page and eventually the app loads.  when i go to the paperless URl, i get a 404 error.   my guess is i am missing something simple, but i just can't find it.  

**Context**
 - Sablier version: 1.6.0
 - Provider: docker v27.5.1 swarm 
 - Reverse proxy: traefik v3.3.3
 - Sablier running inside a container? Yes

**Expected behavior**
Both apps to work...
