### ISSUE TITLE
Default waiting even if service is detected started

### ISSUE THREAD

**Issue by Rollbacke** [sablierapp/sablier#541]
**Describe the bug**
When accessing a service that is turned off, which starts instantly or quickly (for example gitea).
The Sablier page does not display and it sends gitea, but which I believe has not actually started completely, and it displays HTML.
If I refresh again, I have my page that displays normally, but I must admit that it is not practical, that is not the goal!
I have this problem on gitea, bazarr and komga in particular.
I use Traefik.

`docker-compose.yml`:

```
  sablier:
    container_name: sablier
    image: sablierapp/sablier:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      - start
      - --provider.name=docker
      - --provider.auto-stop-on-startup=true
    networks:
      net-bridge:
    restart: unless-stopped

  gitea:
    container_name: gitea
    image: gitea/gitea:latest
    depends_on:
      - sablier
    labels:
      - "sablier.enable=true"
    networks:
      net-bridge:
        ipv4_address: 10.x.x.x
    restart: unless-stopped

  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:development
    depends_on:
      - sablier
    labels:
      - "sablier.enable=true"
    networks:
      net-bridge:
        ipv4_address: 10.x.x.x
    restart: unless-stopped
```

I tried both approaches (dynamic and blocking), traefik `dynamic.yml` file:

```
http:
  middlewares:
    sablier-gitea:
      plugin:
        sablier:
          names: gitea,gitea-psql
          blocking:
            timeout: 1m
          sablierUrl: http://sablier:10000
          sessionDuration: 60m
    sablier-bazarr:
      plugin:
        sablier:
          names: bazarr
          dynamic:
            displayName: Bazarr
            refreshFrequency: 2s
            showDetails: "true"
            theme: hacker-terminal
          sablierUrl: http://sablier:10000
          sessionDuration: 120m

  services:
    gitea-http:
      loadBalancer:
        servers:
          - url: "http://10.x.x.x:3000"
    bazarr-http:
      loadBalancer:
        servers:
          - url: "http://10.x.x.x:6767"

  routers:
    gitea-http:
      rule: "Host(`gitea.myfqdn`)"
      entryPoints:
        - http
      middlewares:
        - redirect-https
      service: gitea-http
    gitea-https:
      rule: "Host(`gitea.myfqdn`)"
      entryPoints:
        - https
      tls:
        certresolver: myresolver
      middlewares:
        - sablier-gitea
      service: gitea-http
    bazarr-http:
      rule: "Host(`bazarr.myfqdn`)"
      entryPoints:
        - http
      middlewares:
        - redirect-https
      service: bazarr-http
    bazarr-https:
      rule: "Host(`bazarr.myfqdn`)"
      entryPoints:
        - https
      tls:
        certresolver: myresolver
      middlewares:
        - sablier-bazarr
      service: bazarr-http
```

**Context**
 - Sablier version: 1.8.5
 - Provider: Docker
 - Reverse proxy: traefik 3.3.5
 - Sablier running inside a container: yes

I don't see anything else. Any ideas?
