### ISSUE TITLE
Active container is stopped

### ISSUE THREAD

**Issue by mr-valente** [sablierapp/sablier#576]
Not sure if this is a bug, or user error, but first of all, thank you for this amazing service! I managed to get it up and running with Caddy, however, it seems to be stopping containers that are actually still active. For example, to test it out, I booted up Jellyfin with Sablier and started playing a movie. I had set the session duration for 2 minutes, and sure enough, after 2 minutes the container stopped. Is Sablier supposed to check if a container is still active before shutting it down, even if it's past the session duration? Or am I doing something wrong?

My Jellyfin Caddyfile block (for testing purposes:

```
jellyfin.mydomain.net {
	route / {
		sablier http://myserver:34690 {
			group jellyfin
			session_duration 2m
			dynamic
		}
	}
	reverse_proxy myserver:32390
}
```

My `sablier.yaml`:

```
provider:
  name: docker 
server:
  port: 34690 
  base-path: /
storage:
  file:
sessions:
  default-duration: 1h
  expiration-interval: 5m
logging:
  level: trace
strategy:
  dynamic:
    custom-themes-path:
    show-details-by-default: true
    default-theme: shuffle
    default-refresh-frequency: 5s
  blocking:
    default-timeout: 1m

```
