### ISSUE TITLE
No waiting page at all

### ISSUE THREAD

**Issue by schumi2004** [sablierapp/sablier#605]
I'm playing with Sablier and tried different things to get stuff working and now i finally have it the way i like but from the first second i started with Sablier i never got a waiting page (hacker-terminal).
Functionality wise regarding starting and stopping containers everything works except for the waiting page.

What did i do wrong?

sablier compose.yaml
```
  sablier:
    image: sablierapp/sablier:1.9.0
    container_name: sablier
    command:
      - start
      #- --provider.name=docker
      - "--configFile=/sablier.yaml"
    environment:
      - TZ=Europe/Amsterdam  
    networks:
      - proxy
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - ./config/sablier/sablier.yaml:/sablier.yaml
```

Example container:
```
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8282:8080
    networks:
      - proxy
    labels:
      - sablier.enable=true
      - sablier.group=dozzle

networks:
  proxy:
    external: true
```

traefik.yaml
```
experimental:
  plugins:
    sablier:
      moduleName: "github.com/sablierapp/sablier"
      version: "v1.8.5"
```

Traefik middleware:
```
    sablier-dozzle:
      plugin:
        sablier:
          group: dozzle
          sablierUrl: http://sablier:10000
          sessionDuration: 5m
          dynamic:
            displayName: Please wait while the app is loading
            refreshFrequency: 5s
            showDetails: "true"
            theme: hacker-terminal
```

sablier.yaml
```
provider:
  # Provider to use to manage containers (docker, swarm, kubernetes)
  name: docker 
server:
  # The server port to use
  port: 10000 
  # The base path for the API
  base-path: /
storage:
  # File path to save the state (default stateless)
  file:
sessions:
  # The default session duration (default 5m)
  default-duration: 5m
  # The expiration checking interval. 
  # Higher duration gives less stress on CPU. 
  # If you only use sessions of 1h, setting this to 5m is a good trade-off.
  expiration-interval: 20s
logging:
  level: info
strategy:
  dynamic:
    # Custom themes folder, will load all .html files recursively (default empty)
    custom-themes-path:
    # Show instances details by default in waiting UI
    show-details-by-default: false
    # Default theme used for dynamic strategy (default "hacker-terminal")
    default-theme: hacker-terminal
    # Default refresh frequency in the HTML page for dynamic strategy
    default-refresh-frequency: 5s
  blocking:
    # Default timeout used for blocking strategy (default 1m)
    default-timeout: 1m
```
